version: '2.1'
orbs:
  hugo: circleci/hugo@1.3.0
  aws-s3: circleci/aws-s3@3.0.0
jobs:

  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - attach_workspace:
          at: my-site
      - run: ls -lah my-site
      - aws-s3/sync:
          from: "bradking.consulting/public"
          to: 's3://bradking.consulting'

workflows:
  build-deploy:
    jobs:
      - hugo/build:
          html-proofer: false
          source: bradking.consulting/
      - deploy:
          requires:
            - hugo/build
