version: '2.1'
orbs:
  hugo: circleci/hugo@1.3.0
  aws-s3: circleci/aws-s3@3.0.0
jobs:

  deploy:
    docker:
      - image: 'cimg/python:3.6'
    environment:
      SRC_DIRECTORY: "bradking.consulting/public"
      S3_BUCKET_LOCATION: 's3://bradking.consulting'
    steps:
      - checkout
      - aws-s3/sync:
          from: ${SRC_DIRECTORY}
          to: ${S3_BUCKET_LOCATION}

workflows:
  build-deploy:
    jobs:
      - hugo/build:
          html-proofer: false
          source: bradking.consulting/
      #- deploy